name: foodgram

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    # build it monthly: At 04:15 on day-of-month 1.
    - cron: '0 */2 * * *'
    # for testing the event "schedule": run every 15 minutes starting from minute 5 through 59 (0, 15, 30, 45)
    #- cron: '0/15 * * * *'
    #The quick and simple editor

jobs:
    tests:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Set up Python
          uses: actions/setup-python@v2
          with:
            python-version: 3.8

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
        
        - name: Lint with flake8
          run: flake8 --exclude ./tests/,./recipes/migrations/,./foodgram/settings.py

    
    build_and_push_to_docker_hub:
      name: Push Docker image to Docker Hub
      runs-on: ubuntu-latest
      needs: tests
      
      steps:
        - name: Check out the repo
          uses: actions/checkout@v2
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1

        - name: Push to Docker Hub
          uses: docker/build-push-action@v2
          with:
            push: false
            tags: arhangel/foodgram:1.0


    deploy:
      runs-on: ubuntu-latest
      needs: build_and_push_to_docker_hub
      steps:
        - uses: actions/checkout@v2
        - name: set up JDK 11
          uses: actions/setup-java@v2
          with:
            java-version: '11'
            distribution: 'adopt'
        - name: 🤞 Build
          run: | 
                ls
        - name: Check Environment
#          shell: bash
          run: |
                 ls
#                mkdir -p src && \
#                chmod 755 src/$f && \
#                src/$f
        - name: Build
          run: src/build.sh
#          shell: bash
          env:
            PMD_CI_SECRET_PASSPHRASE: ${{ secrets.PMD_CI_SECRET_PASSPHRASE }}
